version: "3.9"

volumes:
  mongo_data:
  tempo-data:


services:

  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://mongo:27017/?directConnection=true
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus
    depends_on:
      - mongo
      - redis
      - prometheus
      - tempo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo:2.3.1
    command: [ "--config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - tempo-data:/var/tempo
      - ./tempo.yaml:/etc/tempo/tempo.yaml:ro
      - ./overrides.yaml:/etc/tempo/tempo-overrides.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
